<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQUxKSjg\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQUxKSjg/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQUxKSjg.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQUxKSjg\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerQUxKSjg\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'QUxKSjg',
    'container.build_id' => 'a8154d47',
    'container.build_time' => 1591296701,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQUxKSjg');
