<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerECtt93x\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerECtt93x/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerECtt93x.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerECtt93x\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerECtt93x\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ECtt93x',
    'container.build_id' => 'bb7e3070',
    'container.build_time' => 1592065666,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerECtt93x');
